version: '3.4'

services:
  employeeapi:
    image: employeeapi
    build:
      context: .
      dockerfile: EmployeeApi/Dockerfile
    ports:
      - "5126:5126"
      - "7126:7126"
    volumes:
    - ./https:/https
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword123
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EmployeeDb;User=sa;Password=YourPassword123;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourPassword123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: